### ISSUE TITLE
hue plots should not show discontinuity when jumping from 0 to 100 or from 100 to 0

### ISSUE THREAD

**Issue by anntzer** [tlambert03/cmap#12]
* cmap version: 0.0.2
* Python version: any
* Operating System: any

### Description

The hue plots, e.g. at https://cmap-docs.readthedocs.io/en/latest/catalog/cyclic/cmocean%3Aphase/#hue-saturation, show a discontinuity when the hue jumps from 0 to 100 or the other way round, but that's an artefact as hues are defined modulo 100 (in the scale here).  It would be nice if the vertical line connecting 0 to 100 was not drawn...

### What I Did

N/A

**Comment by tlambert03** [comment]
Thanks for the note!  Fixed in #13:

<img width="710" alt="Screen Shot 2023-05-06 at 11 14 02 AM" src="https://user-images.githubusercontent.com/1609449/236633603-a06ab6d2-7d02-495b-a68f-5b3d75cbdd5e.png">
