### ISSUE TITLE
Provide API for shifting (cyclic) colormaps

### ISSUE THREAD

**Issue by anntzer** [tlambert03/cmap#17]
* cmap version: 0.0.3
* Python version: any
* Operating System: any

### Description

For cyclic colormaps, a useful operation can be to shift the position of the zero.  For example, CET_C3 maps 0 to white, 0.5 to black, and 1 to white again; one could want to do the opposite (0 and 1 mapped to black, 0.5 mapped to white).
An API such as `cmap.shifted(0.5)` could be useful there (it's up to you how you want to handle the name kwarg, but note that unlike reverse()ing, there can be multiple meaningful shifts).

### What I Did

N/A

**Comment by tlambert03** [comment]
implemented in #52 and will be released shortly.  Sorry for the long delay @anntzer

**Comment by anntzer** [comment]
No worries, thanks!
