### ISSUE TITLE
Addition of Paul Tol's colormaps

### ISSUE THREAD

**Issue by Jhsmit** [tlambert03/cmap#45]
Hi, thanks for developing this very nice library!
I keep installing `matplotlib`/`colorcet` etc etc dependencies to have the full selection of colormaps I like to use :)

One set of color maps I like a lot is from Paul Tol: https://personal.sron.nl/~pault/
Are you willing to add / accept a PR for adding these colormaps?

There is python code provided here: https://personal.sron.nl/~pault/data/tol_colors.py
The code is licensed under BSD but I think the color data themselves should be no problem to add if we include the license?

Is there a preferred format for the colormaps or can be anything accepted by `cmap.Colormap` constructor?

**Comment by tlambert03** [comment]
Hi and thanks!  Yes I'd be more than happy to accept PRs for new colormaps and it would great to have Paul Tol's cmaps.  I guess I never finished the "how to add" part of the FAQ, but you can look through any of the folders in the [data](https://github.com/tlambert03/cmap/tree/main/src/cmap/data) directory for patterns.  Basically, you'll add a new folder (can call it `tol` or whatever you want), and add a `record.json` file (following [this schema](https://github.com/tlambert03/cmap/blob/3b327da98ee81b477e88878255cc31b4457ca3c9/src/cmap/_catalog.py#L52-L61)).  The data itself can either be in the `record.json` itself, or referenced as a python path (see, for example, the [seaborn record](https://github.com/tlambert03/cmap/blob/main/src/cmap/data/seaborn/record.json))

> Is there a preferred format for the colormaps or can be anything accepted by cmap.Colormap constructor?

It can be anything that is accepted by the cmap, I believe the hex values in that `tol_colors.py` should work fine.  It does look like I've used numeric values for almost all of the data in here, but I don't think that's mandatory.

if you run into any issues or confusions, do hesitate to ask.  and thanks!
