### ISSUE TITLE
`_repr_png_` does not respect `interpolation=False`

### ISSUE THREAD

**Issue by Jhsmit** [tlambert03/cmap#46]
```python
import cmap as cm
cm_cmap = cm.Colormap(['#364B9A', '#4A7BB7', '#6EA6CD', '#98CAE1', '#C2E4EF',
                '#EAECCC', '#FEDA8B', '#FDB366', '#F67E4B', '#DD3D2D',
                '#A50026'], interpolation=False)
```
![image](https://github.com/tlambert03/cmap/assets/7881506/10b00d3d-faf4-4712-a666-d14f8feabc0b)

matplotlib result (expected):
```python
cm_cmap.to_matplotlib()
```
![image](https://github.com/tlambert03/cmap/assets/7881506/ecec9099-ec9c-4fcf-a1c6-9ee3e9a2ce6b)

However, 
```python
cmap = cm.Colormap('colorbrewer:Accent_5')
cmap
```

does produce a discrete colors png

**Comment by tlambert03** [comment]
thanks!  i vaguely remember seeing this. will try to fix soon

**Comment by tlambert03** [comment]
fixed, thanks!  Will release after we get the tol colormaps in 👍
