### ISSUE TITLE
Bug: docs catalog pages for `chrisluts` return 404

### ISSUE THREAD

**Issue by psobolewskiPhD** [tlambert03/cmap#5]
* cmap version: N/A
* Python version: N/A
* Operating System: N/A

### Description

Clicking any of the `chrisluts` on the catalog page:
https://cmap-docs.readthedocs.io/en/latest/catalog/
returns 404 error (stable and latest Build #20340125).

However, using the burger menu does allow access, so the files are there, e.g.:
https://cmap-docs.readthedocs.io/en/latest/catalog/sequential/chrisluts%3AI_Blue/

It appears that the links in the catalog page use lower case letters, while the actual file names have caps, so I suspect this could affect other cmaps—if not now, then in the future.

Also, for `chrisluts:I_Red` the link from the catalog uses `chrisluts:ied`

Edit: Here's two of the problematic `div` (the `nav` ones are fine):
<img width="756" alt="image" src="https://user-images.githubusercontent.com/76622105/235434197-3efa181a-9e5b-45c4-bb7d-4aff5b233138.png">

Ah, so the `I_Red` issue is this matching gone awry:
https://github.com/tlambert03/cmap/blob/e1de59853a40c9cddb9c092e7f0d48df7708e7c5/docs/_hooks.py#L56
`self.name` is lowercase (consistent with the 404 issue), so then the `_r` replacement gets the internal `_r` from `_Red`.

Edit2:
the `cmap-name` constructed here is correct:
https://github.com/tlambert03/cmap/blob/e1de59853a40c9cddb9c092e7f0d48df7708e7c5/docs/_hooks.py#L15-L20
but this doesn't use `self.name`

### What I Did

Was clicking the different color maps to see the cool visuals.

**Comment by tlambert03** [comment]
Thanks @psobolewskiPhD !

**Comment by tlambert03** [comment]
annoyingly the case doesn't seem to matter in my dev server 😜

![Uploading Screen Shot 2023-05-01 at 5.30.53 PM.png…]()
