### ISSUE TITLE
Feature: improve ergonomics for cyclic qualitative/categorical colormaps

### ISSUE THREAD

**Issue by andy-sweet** [tlambert03/cmap#54]
* cmap version: 0.2.0
* Python version: 3.9.18
* Operating System: macOS 14.4.1

### Description

I am using cmap to generate a qualitative colormap for integer valued images in a napari plugin. The integer values can be greater than the number of colors in the qualitative/categorical colormap, so I want to cycle through those colors.

I might be missing something in the API, but I found this to be a little awkward right now. I think I need to do something like the following:

```python
from cmap import Colormap
index: int = 0 # but could take any non-negative integer value
colormap = Colormap("colorbrewer:set1_8")
color = colormap(index % len(colormap.color_stops))
```

The main reason I found this awkward is because it is was hard to find `Colormap.color_stops`. Alternatively, I also found `len(tuple(Colormap.iter_colors()))`, but this felt wasteful and even more verbose.

For more context, [see the equivalent lines at a commit in a recent PR](https://github.com/chanzuckerberg/napari-cryoet-data-portal/pull/21/files#diff-c5d5e3e005e0b5e48111e418a2702d9bcc1e0a32d02ed811b858018f08dfc515R27).

### Ideas

I'm not sure what to suggest here since I only just started using `cmap` and I don't want to pollute what is a very concise API.

Adding something like `Colormap.num_colors` is probably enough to make me happy here (where `num_colors` is equal to `len(colormap.color_stops)`).

I also thought of something like `Colormap.cycle(values)` as an alternative to `Colormap.__call__` that would do this automatically, but not sure if I like that either.

### Summary

This is a super nit-picky feature request, so you should feel free to close and move on. The only way I could justify putting more thought in here is if the cyclic mapping is one that is likely to used frequently.

If there is interest, I'm happy to think a bit more and have a go at an implementation.

Otherwise, I am loving cmap and its docsite - the [catalog](https://cmap-docs.readthedocs.io/en/stable/catalog/) and perceptual plots are beautiful!

**Comment by tlambert03** [comment]
absolutely happy to add anything that you would find useful.

> The main reason I found this awkward is because it is was hard to find Colormap.color_stops

oh good point. that doesn't show up in the docs.  That's definitely intended to be a user-facing object.  should fix that (and the other attributes like `category`, `name`, etc...

> `num_colors`, equal to len(colormap.color_stops)).

That seems very reasonable.  `len(self.color_stops)` is already used a couple places internally.  It's an important property that should have a defined public accessor.  `num_colors` works for me.

> I also thought of something like Colormap.cycle(values) as an alternative to Colormap.__call__ that would do this automatically, but not sure if I like that either.

I'm definitely open to something like this as well.  it's a nifty application and as you show here doesn't require a complicated implementation.  I like the name cycle too

> If there is interest, I'm happy to think a bit more and have a go at an implementation.

please do!  thanks!

**Comment by tlambert03** [comment]
Since you're using this in a napari plugin, will it still be useful?  The cycle bit wouldn't export in to_napari right?  Is that fine?

**Comment by andy-sweet** [comment]
> Since you're using this in a napari plugin, will it still be useful? The cycle bit wouldn't export in to_napari right? Is that fine?

Yes. In my case, I'm using this for `Labels` layers and need the new `DirectLabelColormap` (in a slightly funky way where each layer is for a separate label because they can overlap...), so I'm not using `cmap.Colormap.to_napari` anyway.

> please do! thanks!

I'll assign this myself and will see if I can write some docs to go with it that describe how to use this with cyclic colormapping. Might not get to it today, but should have a PR up by the end of the week.
