### ISSUE TITLE
Question compatibility with colorbar of Matplotlib

### ISSUE THREAD

**Issue by Iddingsite** [tlambert03/cmap#57]
* cmap version: 0.2.1
* Python version: 3.11.3
* Operating System: MacOS

### Description

Hi! 
I am trying to use cmap to plot a colorbar with Matplotlib. To do so, I need to create it manually using `plt.cm.ScalarMappable`as in the following MWE. It seems not possible to use plt.cm.ScalarMappable from matplotlib to scale directly the colorbars from cmap. Is there a work-around to this? 

### What I Did

Here the code crash at `sm = plt.cm.ScalarMappable(cmap=colormap, norm=norm)`. If I replace `colormap = Colormap('crameri:roma')` by `colormap = plt.get_cmap('cividis')` (see commented line nb 12) it works as expected.

```
import numpy as np
import matplotlib.pyplot as plt
from cmap import Colormap

# Create a range of x values
x = np.linspace(0, 2 * np.pi, 100)

# Create a range of y values as sine and cosine curves
y = np.array([np.sin(x + phi) for phi in np.linspace(0, np.pi, 10)])

# Create a colormap
# colormap = plt.get_cmap('cividis')
colormap = Colormap('crameri:roma')

# Normalize the y values for the colormap
y_min = np.min(y)
y_max = np.max(y)
normalize_y = (y - y_min) / (y_max - y_min)

fig, ax = plt.subplots(1, 1)

# Plot each curve with a color from the colormap
for i in range(len(y)):
    ax.plot(x, y[i], color=colormap(normalize_y[i][0]))

# Add a colorbar to the plot
norm = plt.Normalize(vmin=y_min, vmax=y_max)
sm = plt.cm.ScalarMappable(cmap=colormap, norm=norm)

cbar = fig.colorbar(sm, ax=ax, shrink=0.95)
fig.show()
```

**Comment by tlambert03** [comment]
hey @Iddingsite, the reason the code is failing at `plt.cm.ScalarMappable(cmap=colormap, norm=norm)` is that the matplotlib `ScalarMappable` class expects the object passed to `cmap` to either be a string or an instance of `matplotlib.colors.Colormap`.  `cmap.Colormap` objects are *not* subclasses of `matplotlib.colors.Colormap` (removing the dependency on matplotlib is one of the primary points of this library).  However, if you want to use it with matplotlib, you can easily cast a `cmap.Colormap` to a matplotlib colormap with `to_mpl()`

so, just change your example to:

```python
sm = plt.cm.ScalarMappable(cmap=colormap.to_mpl(), norm=norm)
```

<img width="752" alt="Screenshot 2024-06-02 at 2 11 34 PM" src="https://github.com/tlambert03/cmap/assets/1609449/1272ee8e-1cf2-49ba-b44c-c3dd4a81cb65">

**Comment by Iddingsite** [comment]
Great, that works like a charm, thx for the quick answer!

**Comment by tlambert03** [comment]
Welcome. 

I did, for what it's worth, look into what it would take for it to "magically" work to pass a cmap colormap to matplotib functions.  But i think it will be too magic and error prone, so using to_mpl is going to be preferred

**Comment by Iddingsite** [comment]
The current syntax sounds reasonable to me. It would probably be worth to add a question in the FAQ section at some points maybe though for new users!
