### ISSUE TITLE
FEAT: Add html repr

### ISSUE THREAD

**Issue by ianhi** [tlambert03/cmap#7]
* cmap version: 0.0.1

### Description
One nice feature of matplotlib colormaps is that when they are `display`ed in a notebook or other context where html makes sense they render themselves for the user. This is acheived through the `__repr__html__` function. it would be great if `cmap` also had this functionality. 

![image](https://user-images.githubusercontent.com/10111092/235573736-b4040289-fb16-471d-8369-5e490d4c7319.png)

matplotlib implements this here:

https://github.com/matplotlib/matplotlib/blob/89452ceb1dad4a00d43c1ab571c5dad076977e52/lib/matplotlib/colors.py#L915

**Comment by tlambert03** [comment]
thanks for the reminder.  I'd like to do this in a way that doesn't pull in a pillow/PIL dependency.  So will probably try the import, and then fall back to a CSS representation if PIL is missing
